"""add sharedreview table

Revision ID: 475f5e213fc3
Revises: 9fb4ff051e54
Create Date: 2025-05-13 16:34:47.070797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475f5e213fc3'
down_revision = '9fb4ff051e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('review_ids', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_review')
    # ### end Alembic commands ###
