"""add sharedreviewentry table

Revision ID: 4c30e1457d3c
Revises: e4e54ddbcd4f
Create Date: 2025-05-13 17:31:26.206029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c30e1457d3c'
down_revision = 'e4e54ddbcd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_review_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_review_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['shared_review_id'], ['shared_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_at', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_review', schema=None) as batch_op:
        batch_op.drop_column('shared_at')

    op.drop_table('shared_review_entry')
    # ### end Alembic commands ###
