"""add image field to restaurant

Revision ID: 9fb4ff051e54
Revises: 2c5fff9d909d
Create Date: 2025-05-11 18:21:17.962988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb4ff051e54'
down_revision = '2c5fff9d909d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('comment')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
